# Site settings
title: À pas feutré
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://apasfeutres.github.io" # the base hostname & protocol for your site
destination: /srv/data/vero/web

permalink: /:path/:basename

# Build settings
markdown: kramdown
