# Site settings
title: À pas feutrés
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.apasfeutres.be" # the base hostname & protocol for your site
destination: /srv/data/vero/web


# Build settings
markdown: kramdown


